### ISSUE TITLE
Gitlab Website Down 

### ISSUE THREAD

**Issue by char-mines** [SnowBlinderP/OpenAudioMC-Youtube#2]
i have tried a few times today and the download website is down can i plz get a release here or fix website

**Comment by SnowBlinderP** [comment]
Hi @ilikestohack,

**Thanks for Bringing this to My Attention.**
Im Sorry to hear that you are Having Problems reaching my Plattform.

Could you try the Link in the README again? [SnowDNS Gitlab](https://git.snowdns.de/SnowBlinderP/openaudioyt-addon/-/jobs/artifacts/master/browse?job=Create-And-Save)

I'm already working on Fine-Tuning my Monitoring so this will never happen again.

Best Wishes from Germany,
Snow ❄⛄

**Comment by char-mines** [comment]
thanks its working now
have a good day

**Comment by SnowBlinderP** [comment]
Hi @ilikestohack,
I'm Happy to hear that your Problem could be resolved.

If you have any Issues again ->
Just send me a Message on Discord or Tag me on the Official OpenAudioMC Discord Server [https://discord.gg/9dkdpyk](https://discord.gg/9dkdpyk)

Best Wishes from Germany,
Snow ❄⛄
